<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>教务系统</title>

		<!-- basic styles -->
		<link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="/assets/css/font-awesome.min.css" />
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<!--[if IE 7]>
		  <link rel="stylesheet" href="/assets/css/font-awesome-ie7.min.css" />
		<![endif]-->

		<!-- page specific plugin styles -->

		<!-- fonts -->

		<link rel="stylesheet" href="http://fonts.useso.com/css?family=Open+Sans:400,300" />

		<!-- ace styles -->

		<link rel="stylesheet" href="/assets/css/ace.min.css" />
		<link rel="stylesheet" href="/assets/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="/assets/css/ace-skins.min.css" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="/assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->

		<script src="/assets/js/ace-extra.min.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="/assets/js/html5shiv.js"></script>
		<script src="/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>

		<div class="navbar navbar-default" id="navbar">
<script type="text/javascript">
try{ace.settings.check('navbar' , 'fixed')}catch(e){}
</script>
<script type="text/javascript">
if("ontouchend" in document) document.write("<script src='/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>

			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="#" class="navbar-brand">
						<small>
							<i class="icon-leaf"></i>
							教务系统
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
<script type="text/javascript">
try{ace.settings.check('main-container' , 'fixed')}catch(e){}
</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
<script type="text/javascript">
try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
</script>

					<div class="sidebar-shortcuts" id="sidebar-shortcuts">
						<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
							<button class="btn btn-success">
								<i class="icon-signal"></i>
							</button>

							<button class="btn btn-info">
								<i class="icon-pencil"></i>
							</button>


					<button class="btn btn-warning">
						<i class="icon-group"></i>
					</button>
							<button class="btn btn-danger">
								<i class="icon-cogs"></i>
							</button>
						</div>

						<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
							<span class="btn btn-success"></span>

							<span class="btn btn-info"></span>

							<span class="btn btn-warning"></span>

							<span class="btn btn-danger"></span>
						</div>
					</div><!-- #sidebar-shortcuts -->
<script type="text/javascript">
try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
</script>
				</div>

				<div class="main-content">
<script type="text/javascript">
try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
</script>


<script>
$(document).ready(function(){
	$("#nav-search-input").on("keyup", function() {
		var value = $(this).val().toLowerCase();
		$("#sample-table-2 #mytr").filter(function() {
			$(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
		});
	});
});
</script>

	<div class="page-content">
								<div class="row">
									<div class="col-xs-12">
										<div class="table-responsive">
<div class="table-header">
学生信息
</div>
<div class="table-responsive">
<table id="sample-table-3" class="table table-striped table-bordered table-hover">

<thead>
<tr>
<th class="col-sm-1">志愿课程id</th>
<th class="col-sm-1">课程名</th>
<th class="col-sm-1">开课时间</th>
<th class="col-sm-1">课时</th>
<th class="col-sm-1">学生学号</th>
<th class="col-sm-1">学生姓名</th>
<th class="col-sm-1">评定状态</th>
<th class="col-sm-1"></th>
</tr>
</thead>
<tbody>
<?php
$j=1;
session_start();
echo "<input style='display:none' id='tid' value='".$_SESSION['num']."'/>";
echo "<input style='display:none' id='tname' value='".$_SESSION['name']."'/>";
foreach($this->res as $row)
{
	echo "<tr id='tr".$j."'>";
	foreach($row as $key=>$value)
	{
		if($key == 'workReport')
			continue;
		if($value == 'allow')
			$value = '合格';
		elseif($value == 'refuse')
			$value = '不合格';
		elseif($value == 'wating') 
			$value = '待审核';
		echo "<td value='".$value."'>".$value."</td>";
	}
	echo "<td style='display:none' id='td".$j."'>".$row['workReport']."</td>";
	echo "<td class='col-sm-1'><button id='".$j."' onclick='judge(this)' class='btn btn-sm btn-info form-control' data-toggle='modal' data-dismiss='modal' data-target='#myModal' ><i class='icon-cloud-upload'></i>评价</button></td>";
	echo "</tr>";
	$j++;
}
?>

<script>
				function judge(ctr)
									{
									var id=ctr.id;
									var tab=document.getElementById("sample-table-3");
									var row=tab.rows;
									var cid=row[id].cells[0].innerText;
									var cname=row[id].cells[1].innerText;
									var stuid=row[id].cells[4].innerText;
									var stuname=row[id].cells[5].innerText;
									document.getElementById("form-field-3").value=cid;
									document.getElementById("form-field-4").value=cname;
									document.getElementById("form-field-1").value=stuid;
									document.getElementById("form-field-2").value=stuname;
								}
</script>
</tbody>
</table>
<a href='/tea/Tea/index'><button type='button' class='btn btn-sm btn-danger pull-left' id='".$j."'><i class='icon-remove'></i>返回</button></a>
</div>

<script type="text/javascript">
window.alert = function(str){
	return ;
}
function gao(ctrl)
{
	var id = ctrl.id;
	var tab=document.getElementById("sample-table-2");
	var rows = tab.rows;

	var cid = rows[id].cells[0].innerHTML;
	var uid = rows[id].cells[4].innerHTML;
	result=[];
	result.push(cid);
	result.push(uid);
	result.push("allow");
	var httpRequest = new XMLHttpRequest();
	httpRequest.open("POST","<?php echo $this->url('tea/defaults',array('controller'=>'Tea','action'=>'submit'));?>", true);
			httpRequest.setRequestHeader("Content-type","application/json");
			httpRequest.send(JSON.stringify(result));
	// console.log(result);
httpRequest.onreadystatechange = function () {
	if (httpRequest.readyState == 4 && httpRequest.status == 200) {
	window.location.reload();
	}
}
}
</script>

<script type="text/javascript">
function gaoo(ctrl)
{
	var id = "tr" + ctrl.id;
	var tab = document.getElementById(id);
	console.log(tab);

}
</script>


										</div><!-- /.modal-content -->



							</div><!-- /.col -->
						</div><!-- /.row -->

					</div><!-- /.page-content -->


				</div><!-- /.main-content -->
											<form  method="post" id="test_form" action="/stu/Stu/pasubmit" class = "form-horizontal" role="form" enctype="multipart/form-data">
                                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >

											  <input style="display:none" name="stuid" value="" id="my1">
											  <input style="display:none" name="cid" value="" id="my2">
											  <input style="display:none" name="tid" value="" id="my3">
											  <input style="display:none" name="report" value="" id="my4">
                                                       <div class="am-modal-dialog m-auto">
                                                           <div class="modal-content">
                                                               <div class="modal-header">
                                                                   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                                   <h4 class="modal-title pull-left" id="myModalLabel">助教工作评定表</h4>
                                                               </div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-1" >研究生姓名</label>
                                                                   <div class="col-sm-9">
																   <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" name="stuname" disabled="disabled" value="" />
                                                                   </div>
                                                               </div>
                                                               <div class="space-4"></div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-2">研究生学号</label>
                                                                   <div class="col-sm-9">
																   <input type="text" id="form-field-2" class="col-xs-10 col-sm-5" disabled="disabled" value=""/>
                                                                   </div>
                                                               </div>
                                                               <div class="space-4"></div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-3">课程id</label>
                                                                   <div class="col-sm-9">
                                                                       <input type="text" id="form-field-3" class="col-xs-10 col-sm-5"  disabled="disabled" value=""/>
                                                                   </div>
                                                               </div>
                                                               <div class="space-4"></div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-3">课程名字</label>
                                                                   <div class="col-sm-9">
                                                                       <input type="text" id="form-field-4" class="col-xs-10 col-sm-5" name="cname" disabled="disabled" value=""/>
                                                                   </div>
                                                               </div>
                                                               <div class="space-4"></div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-3">老师id</label>
                                                                   <div class="col-sm-9">
                                                                       <input type="text" id="form-field-5" class="col-xs-10 col-sm-5"  disabled="disabled" value=""/>
                                                                   </div>
                                                               </div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-3">授课教师</label>
                                                                   <div class="col-sm-9">
                                                                       <input type="text" id="form-field-6" class="col-xs-10 col-sm-5"  disabled="disabled" value=""/>
                                                                   </div>
                                                               </div>
                                                               <div class="space-4"></div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-2">助教工作自述</label>
                                                                   <div class="col-sm-4">
																		<!--<input type="textarea" id="form-field-2" class="col-xs-10 col-sm-5" name="report"/>-->
																		<textarea class="form-control col-xs-10 col-sm-5" rows="3" id="form-field-7" disabled="disabled"></textarea>
																		
                                                                   </div>
                                                               </div>

                                                               <div class="space-4"></div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-2">授课教师评价</label>
                                                                   <div class="col-sm-9">
                                                                       <input type="text" id="form-field-8" class="col-xs-10 col-sm-5" name="teajudge"  value=""/>
                                                                   </div>
                                                               </div>
																<div class="space-4"></div>
                                                               <div class="form-group">
                                                                   <label class="col-sm-3 control-label no-padding-right" for="form-field-2">评价</label>
                                                                   <div class="col-sm-9">
																		<div class="form-check">
  <input class="form-check-input" type="radio" name="result" id="flexRadioDefault1">
  <label class="form-check-label" for="flexRadioDefault1">
	合格
  </label>
</div>
<div class="form-check">
  <input class="form-check-input" type="radio" name="result" id="flexRadioDefault2" checked>
  <label class="form-check-label" for="flexRadioDefault2">
不合格
  </label>
</div>
                                                                   </div>
                                                               </div>

                                                           </div>
                                                           <div class="modal-footer mx-auto">
                                                               <button type="button" class="btn btn-default" data-dismiss="modal"><i class="icon-remove"></i>关闭</button>
                                                               <button type="submit" class="btn btn-primary" name="Submit" onclick="gao(this)"><i class="icon-ok"></i>提交更改</button>
                                                           </div>
                                                       </div><!-- /.modal-content -->
                                                   </div><!-- /.modal -->
                                               </form>
				<div class="ace-settings-container" id="ace-settings-container">
					<div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
						<i class="icon-cog bigger-150"></i>
					</div>

					<div class="ace-settings-box" id="ace-settings-box">
						<div>
							<div class="pull-left">
								<select id="skin-colorpicker" class="hide">
									<option data-skin="default" value="#438EB9">#438EB9</option>
									<option data-skin="skin-1" value="#222A2D">#222A2D</option>
									<option data-skin="skin-2" value="#C6487E">#C6487E</option>
									<option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
								</select>
							</div>
							<span>&nbsp; Choose Skin</span>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
							<label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
							<label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs" />
							<label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" />
							<label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-add-container" />
							<label class="lbl" for="ace-settings-add-container">
								Inside
								<b>.container</b>
							</label>
						</div>
					</div>
				</div><!-- /#ace-settings-container -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->

		<script src="http://ajax.useso.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

		<!-- <![endif]-->

		<!--[if IE]>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

		<!--[if !IE]> -->

<script type="text/javascript">
window.jQuery || document.write("<script src='/assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
</script>
<script>
if ( window.history.replaceState ) {
	window.history.replaceState( null, null, window.location.href );
}
</script>
		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='/assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
if("ontouchend" in document) document.write("<script src='/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>
		<script src="/assets/js/bootstrap.min.js"></script>
		<script src="/assets/js/typeahead-bs2.min.js"></script>

		<!-- page specific plugin scripts -->

		<script src="/assets/js/jquery.dataTables.min.js"></script>
		<script src="/assets/js/jquery.dataTables.bootstrap.js"></script>

		<!-- ace scripts -->

		<script src="/assets/js/ace-elements.min.js"></script>
		<script src="/assets/js/ace.min.js"></script>

		<!-- inline scripts related to this page -->

<script type="text/javascript">
jQuery(function($) {
	var oTable1 = $('#sample-table-2').dataTable( {
	"aoColumns": [
{ "bSortable": false },
null, null,null, null, null,
{ "bSortable": false }
] } );


	$('table th input:checkbox').on('click' , function(){
		var that = this;
		$(this).closest('table').find('tr > td:first-child input:checkbox')
			.each(function(){
				this.checked = that.checked;
				$(this).closest('tr').toggleClass('selected');
			});

	});


	$('[data-rel="tooltip"]').tooltip({placement: tooltip_placement});
	function tooltip_placement(context, source) {
		var $source = $(source);
		var $parent = $source.closest('table')
			var off1 = $parent.offset();
		var w1 = $parent.width();

		var off2 = $source.offset();
		var w2 = $source.width();

		if( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';
		return 'left';
	}
})

</script>



	<div style="display:none"><script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540' language='JavaScript' charset='gb2312'></script></div>
</body>
</html>
