<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<link rel="stylesheet" href="http://fonts.useso.com/css?family=Open+Sans:400,300" />



	</head>
	<!-- Le styles -->
<?php echo $this->headLink(array('rel'=>'shortcut icon','type'=>'image/vnd.microsoft.icon','href'=>$this->basePath().'/img/favicon.ico'))
->prependStylesheet($this->basePath().'/assets/css/bootstrap.min.css')
->prependStylesheet($this->basePath().'/assets/css/font-awesome.min.css')
->prependStylesheet($this->basePath().'/assets/css/ace.min.css')
->prependStylesheet($this->basePath().'/assets/css/ace-rtl.min.css')
?>

	<!-- Scripts -->
<?php echo $this->headScript()
->prependFile($this->basePath().'/assets/js/bootstrap.min.js')
->prependFile($this->basePath().'/assets/js/typeahead-bs2.min.js')
->prependFile($this->basePath().'/assets/js/jquery-ui-1.10.3.custom.min.js')
->prependFile($this->basePath().'/assets/js/jquery.ui.touch-punch.min.js')
->prependFile($this->basePath().'/assets/js/jquery.slimscroll.min.js')
->prependFile($this->basePath().'/assets/js/jquery.easy-pie-chart.min.js')
->prependFile($this->basePath().'/assets/js/jquery.sparkline.min.js')
->prependFile($this->basePath().'/assets/js/flot/jquery.flot.min.js')
->prependFile($this->basePath().'/assets/js/flot/jquery.flot.pie.min.js')
->prependFile($this->basePath().'/assets/js/flot/jquery.flot.resize.min.js')
->prependFile($this->basePath().'/assets/js/ace-elements.min.js')
->prependFile($this->basePath().'/assets/js/ace.min.js')
; ?>



<body>
		<?php echo $this->content; ?>
	<?php echo $this->inlineScript() ?>
</body>
</html>

