<body class="login-layout">
	<div class="main-container">
		<div class="main-content">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
				<div class="login-container">
					<div class="center">
						<h1>
							<i class="icon-leaf green"></i>
							<span class="red">Ace</span>
							<span class="white">Application</span>
						</h1>
						<h4 class="blue">&copy; Company Name</h4>
					</div>

					<div class="space-6"></div>

						<div class="position-relative">
							<div id="login-box" class="login-box visible widget-box no-border">
								<div class="widget-body">
									<div class="widget-main">
										<h4 class="header blue lighter bigger">
											<i class="icon-coffee green"></i>
											Please Enter Your Information
										</h4>

										<div class="space-6"></div>
<?php
$form=$this->form;
$form->prepare();
$form->setAttribute('action', $this->url('application/default', array('controller'=>'Index','action'=>'process')));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);
?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('num')); ?></dt>
	<dd><?php
		echo $this->formElement($form->get('num'));
		echo $this->formElementErrors($form->get('num'));
		?>
	</dd>
<dt><?php echo $this->formLabel($form->get('password')); ?></dt>
	<dd><?php
		echo $this->formElement($form->get('password'));
		echo $this->formElementErrors($form->get('password'));
		?>
	</dd>
	<dd><?php
		echo $this->formElement($form->get('submit'));
		echo $this->formElementErrors($form->get('submit'));
		?>
	</dd>
</dl>
<?php echo  $this->form()->closeTag() ?>
<!--								<form>
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
														<input type="text" class="form-control" placeholder="Username" />
														<i class="icon-user"></i>
														</span>
													</label>

													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
														<input type="password" class="form-control" placeholder="Password" />
														<i class="icon-lock"></i>
														</span>
													</label>

													<div class="space"></div>

													<div class="clearfix">
														<label class="inline">
														<input type="checkbox" class="ace" />
														<span class="lbl">Remember Me</span>
														</label>

														<button type="button" class="width-35 pull-right btn btn-sm btn-primary">
														<i class="icon-key"></i>
														Login
														</button>
													</div>

													<div class="space-4"></div>
												</fieldset>
											</form> -->

										</div><!-- /widget-main -->

										<div class="toolbar clearfix">
											<div>
												<a href="#" onclick="show_box('forgot-box'); return false;" class="forgot-password-link">
													<i class="icon-arrow-left"></i>
													I forgot my password
												</a>
											</div>

									</div>
									</div><!-- /widget-body -->
								</div><!-- /login-box -->


							</div><!-- /position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->

		<script src="http://ajax.useso.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

		<!-- <![endif]-->

		<!--[if IE]>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

		<!--[if !IE]> -->

<script type="text/javascript">
window.jQuery || document.write("<script src='assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
if("ontouchend" in document) document.write("<script src='assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>

		<!-- inline scripts related to this page -->

<script type="text/javascript">
function show_box(id) {
	jQuery('.widget-box.visible').removeClass('visible');
	jQuery('#'+id).addClass('visible');
}
</script>
	<div style="display:none"><script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540' language='JavaScript' charset='gb2312'></script></div>
</body>
