<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>学籍管理</title>

		<!-- basic styles -->

		<link href="assets/css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="assets/css/font-awesome.min.css" />
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<!--[if IE 7]>
		  <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css" />
		<![endif]-->

		<!-- page specific plugin styles -->

		<!-- fonts -->

		<link rel="stylesheet" href="http://fonts.useso.com/css?family=Open+Sans:400,300" />

		<!-- ace styles -->

		<link rel="stylesheet" href="assets/css/ace.min.css" />
		<link rel="stylesheet" href="assets/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="assets/css/ace-skins.min.css" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->

		<script src="assets/js/ace-extra.min.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="assets/js/html5shiv.js"></script>
		<script src="assets/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>

		<div class="navbar navbar-default" id="navbar">
<script type="text/javascript">
try{ace.settings.check('navbar' , 'fixed')}catch(e){}
</script>

			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="#" class="navbar-brand">
						<small>
							<i class="icon-leaf"></i>
							Ace Admin
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
<script type="text/javascript">
try{ace.settings.check('main-container' , 'fixed')}catch(e){}
</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
<script type="text/javascript">
try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
</script>

					<div class="sidebar-shortcuts" id="sidebar-shortcuts">
						<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
							<button class="btn btn-success">
								<i class="icon-signal"></i>
							</button>

							<button class="btn btn-info">
								<i class="icon-pencil"></i>
							</button>

							
					<button class="btn btn-warning">
						<i class="icon-group"></i>
					</button>
							<button class="btn btn-danger">
								<i class="icon-cogs"></i>
							</button>
						</div>

						<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
							<span class="btn btn-success"></span>

							<span class="btn btn-info"></span>

							<span class="btn btn-warning"></span>

							<span class="btn btn-danger"></span>
						</div>
					</div><!-- #sidebar-shortcuts -->
<ul class="nav nav-list">
						<li class="active">
						<a href="<?php echo $this->url('root/defaults', array('controller'=>'Root','action'=>'index')) ?>">
								<i class="icon-dashboard"></i>
								<span class="menu-text"> 控制台 </span>
							</a>
						</li>


						<li class="active open">
							<a href="#" class="dropdown-toggle">
								<i class="icon-list"></i>
								<span class="menu-text"> 登陆信息 </span>

							</a>

						</li>
								<li>
								<a href="<?php echo $this->url('root/defaults',array('controller'=>'Root','action'=>'info'));  ?>">
										<i class="icon-user"></i>
										个人资料
									</a>
</li>
								<li>
									<a href="<?php echo $this->url('root/defaults',array('controller'=>'Root','action'=>'login')); ?>">
										<i class="icon-off"></i>
										退出
									</a>
								</li>
							</ul>



<script type="text/javascript">
try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
</script>
				</div>

				<div class="main-content">
					<div class="breadcrumbs" id="breadcrumbs">
<script type="text/javascript">
try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
</script>

						<ul class="breadcrumb">
							<li>
								<i class="icon-home home-icon"></i>
								<a href="#">Home</a>
							</li>

							<li>
								<a href="#">Login</a>
							</li>
						</ul><!-- .breadcrumb -->

						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
<script>
  $(document).ready(function(){
    $("#nav-search-input").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#sample-table-2 #mytr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>
									<i class="icon-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- #nav-search -->
					</div>
										<?php
// if($this->num){
	// echo $this->num . " " . $this->name . " " .$this->identity;
// }
if($this->error !== '#'){
header("content-type:text/html;charset=utf-8");
echo '<script type="text/javascript">';

echo 'alert("'.$this->error;
foreach($this->arr as $i)
	echo $i;
echo '");';
echo '</script>';
$this->error = '#';
}
										?>


					<div class="page-content">
								<div class="row">
									<div class="col-xs-12">
										<div class="table-header">
											Login Information
										</div>
										<div class="table-responsive">
											<table id="sample-table-2" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														<th class="center col-sm-1">
															<label>
																<input type="checkbox" class="ace" />
																<span class="lbl"></span>
															</label>
														</th>
														<th class="col-sm-2">学号</th>
														<th class="col-sm-2">姓名</th>

														<th class="col-sm-2">
															密码
														</th>

														<th class="col-sm-2">身份</th>
														<th class="col-sm-2">重置密码</th>
													</tr>
												</thead>

												<tbody>
<?php
// $res = $this->res;
// $res = fetchstu() ;
$row = array();
foreach($this->res as $row){
// while($row--){
	echo "<tr id='mytr'> <td class='center'>
		<label>
		<input type='checkbox' class='ace' />
		<span class='lbl'></span>
		</label>
		</td>";
	echo "<td>".$row['uid']."</td><td>".$row['uname']."</td><td>".$row['upsd']."</td><td>".$row['utype']."</td>";
	// foreach($row as $value){
	// echo "<td>$value$</td>";
	// }
	echo "
		<td>
		<div class='visible-md visible-lg hidden-sm hidden-xs action-buttons'>

		<a href='#'>
		<i class='icon-undo bigger-120'></i>
		</a>
		</div>

		</td>
		</tr>";
}
?>
												</tbody>
												</table>
											</div>

											<div class="modal-footer no-margin-top">
											<button class="btn btn-sm btn-danger pull-left" data-dismiss="modal" onclick="getselected()" >

													<i class="icon-remove"></i>
													Delete
												</button>

<!-- 按钮触发模态框 -->
<button class="btn btn-sm btn-info pull-left" data-toggle="modal" data-target="#myModal">
	<i class="icon-group"></i>
	Add
</button>

<!-- 模态框（Modal） -->
<form method="post" action="<?php echo $this->url('root/defaults',array('controller'=>'Root','action'=>'add'));?>" class = "form-horizontal" role="form">
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

	<div class="am-modal-dialog m-auto">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title pull-left" id="myModalLabel">用户信息</h4>
			</div>
<div class="form-group">
<label class="col-sm-3 control-label no-padding-right" for="form-field-1">学工号</label>
<div class="col-sm-9">
<input type="text" size="6"  id="form-field-1" class="col-xs-10 col-sm-5" name="num"/>
</div>
</div>
<div class="space-4"></div>
<div class="form-group">
<label class="col-sm-3 control-label no-padding-right" for="form-field-2">姓名</label>
<div class="col-sm-9">
<input type="text" id="form-field-2" class="col-xs-10 col-sm-5" name="name"/>
</div>
</div>
<div class="space-4"></div>
<div class="form-group">
<label class="col-sm-3 control-label no-padding-right pull-left" for="form-firld-3">身份</label>
<div class="col-sm-3">
<select class="form-control " name="identity">
	<option value="graduate_student">学生</option>
	<option value="teather">教师</option>
	<option value="admin">管理员</option>
</select>
</div>
</div>
			<div class="modal-footer mx-auto">
				<button type="button" class="btn btn-default" data-dismiss="modal"><i class="icon-remove"></i>关闭</button>
				<button type="submit" class="btn btn-primary" name="Submit"><i class="icon-ok"></i>提交更改</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
</div>
</div>
</form>




											</div>

										</div><!-- /.modal-content -->



							</div><!-- /.col -->
						</div><!-- /.row -->

					</div><!-- /.page-content -->
				</div><!-- /.main-content -->

				<div class="ace-settings-container" id="ace-settings-container">
					<div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
						<i class="icon-cog bigger-150"></i>
					</div>

					<div class="ace-settings-box" id="ace-settings-box">
						<div>
							<div class="pull-left">
								<select id="skin-colorpicker" class="hide">
									<option data-skin="default" value="#438EB9">#438EB9</option>
									<option data-skin="skin-1" value="#222A2D">#222A2D</option>
									<option data-skin="skin-2" value="#C6487E">#C6487E</option>
									<option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
								</select>
							</div>
							<span>&nbsp; Choose Skin</span>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
							<label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
							<label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs" />
							<label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" />
							<label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-add-container" />
							<label class="lbl" for="ace-settings-add-container">
								Inside
								<b>.container</b>
							</label>
						</div>
					</div>
				</div><!-- /#ace-settings-container -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->

		<script src="http://ajax.useso.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

		<!-- <![endif]-->

		<!--[if IE]>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

		<!--[if !IE]> -->

<script type="text/javascript">
window.jQuery || document.write("<script src='assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
</script>
<script>
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>
		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
if("ontouchend" in document) document.write("<script src='assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>
		<script src="assets/js/bootstrap.min.js"></script>
		<script src="assets/js/typeahead-bs2.min.js"></script>

		<!-- page specific plugin scripts -->

		<script src="assets/js/jquery.dataTables.min.js"></script>
		<script src="assets/js/jquery.dataTables.bootstrap.js"></script>

		<!-- ace scripts -->

		<script src="assets/js/ace-elements.min.js"></script>
		<script src="assets/js/ace.min.js"></script>

		<!-- inline scripts related to this page -->

<script type="text/javascript">
jQuery(function($) {
	var oTable1 = $('#sample-table-2').dataTable( {
	"aoColumns": [
{ "bSortable": false },
null, null,null, null, null,
{ "bSortable": false }
] } );


	$('table th input:checkbox').on('click' , function(){
		var that = this;
		$(this).closest('table').find('tr > td:first-child input:checkbox')
			.each(function(){
				this.checked = that.checked;
				$(this).closest('tr').toggleClass('selected');
			});

	});


	$('[data-rel="tooltip"]').tooltip({placement: tooltip_placement});
	function tooltip_placement(context, source) {
		var $source = $(source);
		var $parent = $source.closest('table')
			var off1 = $parent.offset();
		var w1 = $parent.width();

		var off2 = $source.offset();
		var w2 = $source.width();

		if( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';
		return 'left';
	}
})
	</script>
<form method="post" name="hidresult" style="display:hidden;visibility:hidden" action="<?php echo $this->url('root/defaults',array('controller'=>'Root','action'=>'delete'));?>">
        <input type="text" name="tags" style="display:hidden;visibility:hidden" value="arr[]" />
    </form>
    </html>

	<?php
header("content-type:text/html;charset=utf-8");
echo '<script type="text/javascript">';
echo ' function getselected()
        {
            var tab=document.getElementById("sample-table-2");

            var rows = tab.rows;
			var result = [];
            for(var i = 1; i < rows.length; i++)
            {
				var j = rows[i].cells[0].getElementsByTagName("label");
                var obj = j[0].getElementsByTagName("input");
                if(obj[0].checked)
				{
					j = rows[i].cells[1];
                    result.push(rows[i].cells[1].outerText);
                }
			}
			console.log("goose");
			var httpRequest = new XMLHttpRequest();
			httpRequest.open("POST","'.$this->url("root/defaults",array("controller"=>"Root","action"=>"delete")).'", true);
			httpRequest.setRequestHeader("Content-type","application/json");
			httpRequest.send(JSON.stringify(result));
httpRequest.onreadystatechange = function () {
    if (httpRequest.readyState == 4 && httpRequest.status == 200) {
    window.location.reload();
    }
};
		}';
echo '</script>';

?>
<script>
          </script>
	<div style="display:none"><script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540' language='JavaScript' charset='gb2312'></script></div>
</body>
</html>
