<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>登陆界面</title>

		<link rel="stylesheet" href="http://fonts.useso.com/css?family=Open+Sans:400,300" />



	</head>
	<!-- Le styles -->
<?php echo $this->headLink(array('rel'=>'shortcut icon','type'=>'image/vnd.microsoft.icon','href'=>$this->basePath().'/img/favicon.ico'))
->prependStylesheet($this->basePath().'/css/style.css')
->prependStylesheet($this->basePath().'/css/bootstrap-theme.min.css')
->prependStylesheet($this->basePath().'/css/bootstrap.min.css')
->prependStylesheet($this->basePath().'/assets/css/bootstrap.min.css')
->prependStylesheet($this->basePath().'/assets/css/font-awesome.min.css')
->prependStylesheet($this->basePath().'/assets/css/ace.min.css')
->prependStylesheet($this->basePath().'/assets/css/ace-rtl.min.css')
?>

	<!-- Scripts -->
<?php echo $this->headScript()
->prependFile($this->basePath().'/js/bootstrap.min.js')
->prependFile($this->basePath().'/js/jquery.min.js')
->prependFile($this->basePath().'/js/respond.min.js','text/javascript',array('conditional'=>'It IE 9',))
->prependFile($this->basePath().'/js/html5shiv.js', 'text/javascript', array('conditional'=>'It IE 9',))
; ?>



</head>
<body>
	<div class="container">
		<?php echo $this->content; ?>
	</div> <!--/container-->
	<?php echo $this->inlineScript() ?>
</body>
</html>

